--- #YAML:1.0
name:               HTTP-Request-AsCGI
version:            0.501
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:             0
    Class::Accessor:  0
    HTTP::Request:    0
    HTTP::Response:   1.53
    IO::File:         0
    Test::More:       0
    URI::Escape:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
